version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    networks: 
      hostinger_network:
    ports:
      - 8080:8080
    container_name: backend-service
  frontend:
    build: ./frontend
    restart: unless-stopped
    networks: 
      hostinger_network:
    container_name: frontend-service
    ports:
      - 80:80
    depends_on:
      - backend
networks:
  hostinger_network: